# https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images
#
name: Build and Push

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['main']

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            home-vscode-stack
          key: ${{ runner.os }}-home-vscode-stack
      
      - run: |
          echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
          mkdir -p home-vscode-stack
          date >> home-vscode-stack/test.txt
          cat -n home-vscode-stack/test.txt 

#      - uses: docker/build-push-action@v6
#        with:
#          context: .
#          push: true
#          platforms: linux/amd64
#          cache-from: type=registry,ref=${{ env.REGISTRY }}/lcamel/github-actions-cache-test:cache
#          cache-to: type=registry,ref=${{ env.REGISTRY }}/lcamel/github-actions-cache-test:cache,mode=max
#          tags: |
#            ${{ env.REGISTRY }}/lcamel/github-actions-cache-test:latest
#          build-args: |
#            BUILDKIT_INLINE_CACHE=1
#          build-contexts: |
#            home-vscode-stack=./home-vscode-stack
#